/*-------------------------------------------------------------------------------------------------------------------*\
|  Copyright (C) 2014 eBay Software Foundation                                                                        |
|                                                                                                                     |
|  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance     |
|  with the License.                                                                                                  |
|                                                                                                                     |
|  You may obtain a copy of the License at                                                                            |
|                                                                                                                     |
|       http://www.apache.org/licenses/LICENSE-2.0                                                                    |
|                                                                                                                     |
|  Unless required by applicable law or agreed to in writing, software distributed under the License is distributed   |
|  on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for  |
|  the specific language governing permissions and limitations under the License.                                     |
\*-------------------------------------------------------------------------------------------------------------------*/

package com.paypal.selion.platform.grid;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.testng.annotations.Test;

import com.paypal.selion.annotations.WebTest;
import com.paypal.selion.platform.grid.SeLionSession;
import com.paypal.selion.platform.grid.Grid;

import static com.paypal.selion.platform.asserts.SeLionAsserts.assertTrue;

public class SeLionSessionTest {

    @WebTest
    @Test(groups = "functional")
    public void testToString() throws IOException {
        Grid.open("about:blank");
        File file = new File("src/test/resources/testdata/InsertHtmlElements.js");
        Grid.driver().executeScript(FileUtils.readFileToString(file));

        SeLionSession session = new SeLionSession(Grid.driver());

        assertTrue(session.toString().contains("title=TestPage Generated By JavaScript"),
                "verify the returned string contians the page Title");
    }
}
